const EventActionTypes = {
  ADD_EVENT: "ADD_EVENT",
  DELETE_EVENT: "DELETE_EVENT",
  SET_ACTIVE_EVENT: "SET_ACTIVE_EVENT",
  ADD_SESSION: "ADD_SESSION",
  DELETE_SESSION: "DELETE_SESSION",
  SET_ACTIVE_SESSION: "SET_ACTIVE_SESSION",
};

export default EventActionTypes;
